name: weather-bot
on:
  push: # push 이벤트 발생 시
    branches:
      - feat-github-actions-작동-테스트#1
  workflow_dispatch:
  # schedule:
  #  - cron: "41 13 * * 1"

jobs:
  post_weather_forecast_message:
    runs-on: ubuntu-latest
    steps:
      - name: action code checkout
        uses: actions/checkout@v3

      - name: create .env file
        run: |
          echo "SLACK_TOKEN=${{ secrets.SLACK_TOKEN }}" > .env
          echo "SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }}" >> .env

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run main.py
        run: python3 main.py
